version: "3.9"

services:
  django:
    build: .
    image: "django-react"
    restart: always
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8000:8000"
  redis:
    image: redis:5.0
    volumes:
      - redis-data:/usr/local/etc/redis
    ports:
      - "6379:6379"
volumes:
  redis-data: {}